Update and cleanup docker files
ARMmbed/mbedtls-test pull request #31
Opened 2022-01-14 13:51 UTC by minosgalanakis

This PR is implementing the following:

### Changes

* Align 16.04 to 18.04 Docker images
* Remove 16.04 related workarounds when possible
* Updated the ARMLMD_LICENSE_FILE files and removed workarounds in groovy scripts
* Created a 20.04 Docker Image file which is fully aligned to 18.04
* Added the `--security-opt seccomp=unconfined` to the docker run parameter
* Switched to distribution provided versions for abi-dumper, abi-compliance-checker libasn1

### Testing

Image are tested locally using the build and run scripts, and isolated builds

### Todo

Test the 18.04 and 20.04 on the CI and capture if the all.sh is passing

2022-01-18 10:28 UTC, minosgalanakis commented
### Failure investiagations

The following code was added to the get_release_jobs method in order to test including 20.04 images

`def gen_release_jobs(label_prefix='', run_examples=true) {
    def jobs = [:]

    common.get_branch_information()

    if (env.RUN_BASIC_BUILD_TEST == "true") {
        jobs = jobs + gen_code_coverage_job('ubuntu-16.04');
    }

    if (env.RUN_ALL_SH == "true") {
        for (component in (common.available_all_sh_components['ubuntu-20.04'])) {
            jobs = jobs + gen_all_sh_jobs('ubuntu-20.04', component, label_prefix)
        }

        for (component in (common.available_all_sh_components['ubuntu-16.04'] -
                           common.available_all_sh_components['ubuntu-20.04'])) {
            jobs = jobs + gen_all_sh_jobs('ubuntu-16.04', component, label_prefix)
         }

        for (component in (common.available_all_sh_components['ubuntu-18.04'] -
                           common.available_all_sh_components['ubuntu-20.04'] -
                           common.available_all_sh_components['ubuntu-16.04'])) {
            jobs = jobs + gen_all_sh_jobs('ubuntu-18.04', component, label_prefix)
         }
    }`

Job [352 ](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/352/)only tested 20.4 and [353 ](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/353/)tested previous docker platforms as well

The following items are currently failing with 20.04 image
* all_u20-check_doxygen
* all_u20-test_everest
* all_u20-test_se_default

### all_u20-check_doxygen

This is a known issue with newer versions of doxygen as reported in mbedtls issue [\#3497](https://github.com/ARMmbed/mbedtls/issues/3497)

### all_u20-test_everest

The test appears to fail by a runtime error [full_log](https://jenkins-mbedtls.oss.arm.com/blue/rest/organizations/jenkins/pipelines/mbedtls-release-ci-testing/runs/353/nodes/245/steps/946/log/?start=0)

~~~~~
PSA cipher encrypt: invalid key type .............................. /var/lib/build/library/psa_crypto.c:3595:16: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /var/lib/build/library/psa_crypto.c:3595:16 in 
~~~~~

### all_u20-test_se_default

The test also fails because of a runtime error [full_log](https://jenkins-mbedtls.oss.arm.com/blue/rest/organizations/jenkins/pipelines/mbedtls-release-ci-testing/runs/353/nodes/322/steps/3460/log/?start=0)

~~~~~
test_suite_pkparse ................................................ PASS
test_suite_pkwrite ................................................ PASS
test_suite_poly1305 ............................................... PASS
test_suite_psa_crypto ............................................. psa_crypto.c:3595:16: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior psa_crypto.c:3595:16 in 
FAIL
--------------------- Begin test_suite_psa_crypto ---------------------
~~~~~

2022-01-25 12:38 UTC, mpg reviewed
This was just a first pass, I'll have a look at the test results tomorrow.

2022-01-25 12:38 UTC, mpg commented on resources/docker_files/ubuntu-18.04/Dockerfile
> +# - libtasn1: can use the Ubuntu version
Please leave a note about `--with-included-libtasn1` as a reminder, if in the future we need a bleeding-edge version of GnuTLS for which the Ubuntu version is not enough (like the comment on libunistring below).

2022-01-25 12:38 UTC, mpg commented on resources/docker_files/ubuntu-18.04/Dockerfile
> +RUN apt-get update -q && apt-get install -yq abi-compliance-checker abi-dumper
I think it would be better to add that to the big invocation of `apt-get install` that starts on line 39:
- minimizing the number of times we call `apt-get update` reduces the time it takes to build the image
- I think have everything in one place in a sorted list makes it easier to maintain

2022-01-25 12:38 UTC, mpg commented on resources/docker_files/ubuntu-20.04/Dockerfile
> +RUN apt-get update -q && apt-get install -yq abi-compliance-checker
Same note as for the 18.04 file: let's keep all things installed with `apt` in the same place as much as possible.

2022-01-25 12:38 UTC, mpg commented on resources/docker_files/ubuntu-18.04/Dockerfile
> +RUN apt-get update -q && apt-get install -yq abi-compliance-checker abi-dumper
More importantly: the 16.04 says we want at least version 2.3 of `abi-compliance-checker`. Unless I'm mistaken, Ubuntu 18.04 only has 2.2. So, shouldn't we still compile 2.3?

(OTOH, `abi-dumper` seems OK as the Ubuntu repos have 1.1.)

2022-02-04 18:38 UTC, gilles-peskine-arm requested changes
I reviewed the code changes. I haven't inspected CI results. Have you run the CI with the latest version? If not, please update the PR description once you do. You might wait until you've handled the review feedback.

2022-02-04 18:38 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-18.04/Dockerfile
> -# Ubuntu 18.04's pip (9.0.1) doesn't support suppressing the progress bar,
This sentence is still relevant.

2022-02-04 18:38 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-20.04/Dockerfile
> +RUN apt-get install -yq abi-dumper
Already done above.

2022-02-04 18:38 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-20.04/Dockerfile
> +RUN python3 -m pip install pip --upgrade | cat && \
Ubuntu 20.04 comes with pip 20.0.2. We don't need to upgrade pip here.

2022-02-04 18:38 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-20.04/Dockerfile
> +        abi-compliance-checker \
```suggestion
        # for Mbed TLS tests
        abi-compliance-checker \
        # to use with abi-compliance-checker
        abi-dumper \
```

2022-02-04 18:38 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-20.04/Dockerfile
> +        # to install the preferred version of pylint
Preexisting: not just pylint.
```suggestion
        # to install several Python packages (done by individual jobs)
```

2022-02-04 18:38 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-20.04/Dockerfile
> +    python3 -m pip install mypy==0.780 && \
Preexisting: any branch forked from a maintained branch since 2021-12-03 (which is before the last release) no longer needs `pylint` or `mypy` installed from the Docker image. Test jobs now take care of installing the Python packages they need. They just assume that pip (and setuptools?) is present. So I think we can remove the installation of pylint and mypy from the 16.04 and 18.04 images, and not add them to the 20.04 image.

2022-02-04 18:38 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-20.04/Dockerfile
> +        abi-compliance-checker \
[The Ubuntu 20.04 versions of the abi tools are known not to work: our test script always passes even when it should report problems](https://github.com/ARMmbed/mbedtls/issues/5332). I'm ok with not mentioning this in the Docker image, but we do need to keep this in mind, and in particular we must not switch the ABI check job to the Ubuntu 20.04 image until this is resolved. I'd prefer to comment out the installation of `abi-dumper` and `abi-compliance-checker` in the Ubuntu 20.04 image for now, with a comment linking to the known issue.

I haven't tested how the ABI job behaves on Ubuntu 18.04.

2022-02-04 18:38 UTC, gilles-peskine-arm commented on resources/docker_files/run.sh
> +sudo docker run --network=host --rm -i -t -u $USR_ID:$USR_GRP -w /var/lib/ws -v $MOUNT_DIR:/var/lib/ws -v $SSH_CFG_PATH:/home/user/.ssh --cap-add SYS_PTRACE --security-opt seccomp=unconfined ${IMAGE}
Assuming we do need to disable ASLR:

What are the security implications of ``-security-opt seccomp=unconfined`? Why wasn't it needed before? Is there a way to only allow disabling ASLR, and keep the rest of seccomp (https://security.stackexchange.com/questions/214923/disable-aslr-inside-docker-container suggests that there is)?

2022-02-04 18:38 UTC, gilles-peskine-arm commented on resources/docker_files/README.md
> +Note that the additional parameter `--security-opt seccomp=unconfined` which is disabling the ASLR for the zeroize test, is now set by default.
The zeroize test doesn't need to disable ASLR. According to `all.sh`:

```
    # Don't try to disable ASLR. We don't care about ASLR here. We do care
    # about a spurious message if Gdb tries and fails, so suppress that.
    gdb_disable_aslr=
    if [ -z "$(gdb -batch -nw -ex 'set disable-randomization off' 2>&1)" ]; then
        gdb_disable_aslr='set disable-randomization off'
    fi
```

2022-02-07 15:37 UTC, minosgalanakis commented on resources/docker_files/ubuntu-20.04/Dockerfile
> +RUN python3 -m pip install pip --upgrade | cat && \
Removed that line as well as the preceeding text which becomes irrelevant to the code.

2022-02-07 15:37 UTC, minosgalanakis commented on resources/docker_files/ubuntu-18.04/Dockerfile
> -# Ubuntu 18.04's pip (9.0.1) doesn't support suppressing the progress bar,
Fixed

2022-02-07 15:59 UTC, minosgalanakis commented on resources/docker_files/run.sh
> +sudo docker run --network=host --rm -i -t -u $USR_ID:$USR_GRP -w /var/lib/ws -v $MOUNT_DIR:/var/lib/ws -v $SSH_CFG_PATH:/home/user/.ssh --cap-add SYS_PTRACE --security-opt seccomp=unconfined ${IMAGE}
The requirement to enable this setting came from PRs [130 ](https://github.com/ARMmbed/mbedtls-test-old/pull/139), [192 ](https://github.com/ARMmbed/mbedtls-test-old/pull/192)in the old repo

     Note, to run the `all.sh "test_zeroize"` tests you need to pass the additional parameters ` --cap-add=SYS_PTRACE   --security-opt seccomp=unconfined` to allow ASLR to be disabled for the zeroize test. Without these parameters, this test will always fail.

For the suggestion in stack exchange, from what I gather it needs to have permission to run to the /proc space of the host os which is something very unlikely to be accepted (for security purposes) by the devops teams managing the CI.

On the other hand though, `-security-opt seccomp=unconfined` is pretty equivalent to `--priviledged` fact with regards on security implications, so ideally we shouldn't be enabling it unless needed so.

Should we change the requirements on issue #10 ?

2022-02-07 21:00 UTC, gilles-peskine-arm commented on resources/docker_files/run.sh
> +sudo docker run --network=host --rm -i -t -u $USR_ID:$USR_GRP -w /var/lib/ws -v $MOUNT_DIR:/var/lib/ws -v $SSH_CFG_PATH:/home/user/.ssh --cap-add SYS_PTRACE --security-opt seccomp=unconfined ${IMAGE}
I tried the 18.04 image from this PR with the production `run.sh`, i.e. with `--cap-add SYS_PTRACE` and without `--security-opt`, and it passes. That's on an Ubuntu 20.04 host. The 20.04 image is still building.

To the best of my recollection, [the comment in `all.sh` that states that `test_zeroize` does not need to disable ASLR](https://github.com/ARMmbed/mbedtls-test/pull/31/files#r799717704) is correct.

The statement that `test_zeroize` needs to disable ASLR comes from the description of https://github.com/ARMmbed/mbedtls-test-old/pull/130 which never completed its review cycle. This was in part an aggregation of pending updates, so it's possible that it was recycling an old patch. I remember there was a bit of confusion when we added `test_zeroize` because gdb printed an error message stating that it failed to disable ASLR, and that error tripped our scripts. But this was not a fatal error: gdb worked just fine for what we needed it to do even when ASLR was active, we just wanted it not to print the word “error”. Maybe that's where the confusion started.

2022-02-08 09:10 UTC, mpg commented on resources/docker_files/run.sh
> +sudo docker run --network=host --rm -i -t -u $USR_ID:$USR_GRP -w /var/lib/ws -v $MOUNT_DIR:/var/lib/ws -v $SSH_CFG_PATH:/home/user/.ssh --cap-add SYS_PTRACE --security-opt seccomp=unconfined ${IMAGE}
> Should we change the requirements on issue https://github.com/ARMmbed/mbedtls-test/issues/10 ? 

As the person who wrote that issue's description: please don't give it too much weight. As Gilles said, I was mostly trying to collect changes that had been proposed over time but never got merged for various reasons; some of them had not been fully reviewed and may very well be incorrect. So, please read the requirement as "do the minimal amount of changes so that `test_zeroize` can pass locally", rather that "do this specific change". Sorry, in hindsight I could have worded that better.

2022-02-08 21:52 UTC, minosgalanakis commented on resources/docker_files/ubuntu-20.04/Dockerfile
> +    python3 -m pip install mypy==0.780 && \
Fixed on a separate commit

2022-02-08 21:58 UTC, minosgalanakis commented on resources/docker_files/README.md
> +Note that the additional parameter `--security-opt seccomp=unconfined` which is disabling the ASLR for the zeroize test, is now set by default.
Addressed by reverting commit [20dd9eb](https://github.com/ARMmbed/mbedtls-test/pull/31/commits/20dd9eb36c9b00632b7ad20d5000184fce9668e4)

2022-02-08 22:11 UTC, minosgalanakis commented
I am quoting @gilles-peskine-arm  from an slack channel thread

> `resources/docker_files/run.sh /some/directory ubuntu-16.04` no longer works out of the box because that results in `HOME` set to `/` which is not writable so installing python modules with scripts/min_requirements.py fails. Can we arrange to set `HOME` to the workspace directory mounted on `/var/lib/ws`

A new requirement/request is accepted to add an ENV entry for `HOME->/var/lib/ws` in all three images. It will be added in a single commit.

2022-02-09 22:35 UTC, gilles-peskine-arm requested changes
Looks good to me except for HOME set to the wrong directory (sorry).

Please run at least a pr-merge test job and a release test job with the final version of the images.

2022-02-09 22:35 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +ENV HOME=/var/lib/ws
`/var/lib/ws` doesn't exist by default, and it's a directory outside the Docker image. `/var/lib/builds` is the one that's created by default and owned by `user`. So I think `HOME` should be set to that instead. Sorry, I wasn't thinking properly when I suggested `/var/lib/ws`.

2022-02-21 11:18 UTC, mpg approved these changes
Looks good to me.

I noticed an outdated comment, but we might choose to ignore it for now in order to merge this PR quickly and unblock work that depends on it.

2022-02-21 11:18 UTC, mpg commented on resources/docker_files/ubuntu-18.04/Dockerfile
> +RUN python3 -m pip install pip --upgrade | cat && \
Minor: the comment above is outdated, as it says " Install pip<21" which is no longer what we're doing. (Non-blocker as this is only a comment.)

2022-02-21 12:35 UTC, gilles-peskine-arm commented
@minosgalanakis I notice you've run at least https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/372/ on the latest commit. Can you please make a list of the jobs you've run?

2022-02-21 16:59 UTC, minosgalanakis commented
As requested by @gilles-peskine-arm I am attaching the summary of the testing:

- [x] Test job mbedtls-release-ci-testing [372 ](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbedtls-release-ci-testing/detail/mbedtls-release-ci-testing/372/pipeline)(RUN_BASIC_BUILD_TEST @ 16.04) -> Passed
- [x] Test job mbedtls-release-ci-testing  [372 ](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbedtls-release-ci-testing/detail/mbedtls-release-ci-testing/372/pipeline)(RUN_BASIC_BUILD_TEST @ 18.04) -> Passed
- [x] Test job mbedtls-release-ci-testing  [372 ](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbedtls-release-ci-testing/detail/mbedtls-release-ci-testing/372/pipeline)(RUN_BASIC_BUILD_TEST @ 20.04) -> Passed
- [x] Test job mbedtls-release-ci-testing [348 ](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbedtls-release-ci-testing/detail/mbedtls-release-ci-testing/348/pipeline)(RUN_ALL_SH@ 16.04) -> Passed
- [x] Test job mbedtls-release-ci-testing [348 ](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbedtls-release-ci-testing/detail/mbedtls-release-ci-testing/348/pipeline)(RUN_ALL_SH@ 18.04) -> Passed
- [x] Test job mbedtls-release-ci-testing [348 ](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbedtls-release-ci-testing/detail/mbedtls-release-ci-testing/348/pipeline)(RUN_ALL_SH@ 20.04) -> Passed
- [ ] Testing RUN_ABI_TEST in mbed-tls-pr-test-parametrized [327 ](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-test-parametrized/detail/mbed-tls-pr-test-parametrized/237/pipeline) (RUN_ABI_CHECK) --> Failed
- [x] Testing RUN_ALL in mbed-tls-pr-test-parametrized [327 ](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-test-parametrized/detail/mbed-tls-pr-test-parametrized/237/pipeline) (RUN_ALL_SH@ 16.04) --> Passed
- [x] Testing RUN_ABI_TEST in mbed-tls-pr-test-parametrized [327 ](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-test-parametrized/detail/mbed-tls-pr-test-parametrized/237/pipeline) (RUN_ALL_SH@ 18.04)  --> Passed

The abi-check failure can be reviewed [here](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-test-parametrized/detail/mbed-tls-pr-test-parametrized/237/pipeline/372/)

~~~~~
<problems_with_types severity="High">
  <header name="ssl.h">
    <type name="struct mbedtls_ssl_context">
      <problem id="Removed_Field">
        <change target="client_auth">Field @target has been removed from this type.</change>
        <effect target="client_auth" type_name="struct mbedtls_ssl_context">Recompilation of a client program may be broken with the error message: '@type_name' has no member named '@target'.</effect>
      </problem>
      </type>
  </header>
</problems_with_types>
~~~~~~

I am investigating weather that issue is caused by the tools/versions or the codebase

2022-02-21 17:58 UTC, gilles-peskine-arm commented
[327](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-test-parametrized/237/) attempts to merge bff88ab0862314bca40fbb5976427abe093c9b7b into a7a1deabf8537e7f13b99025727480155b2adcba which is quite a bit older. So API/ABI differences are to be expected.

I'm happy with the positive testing from 327, 372 and 348 for development. We should also check the LTS branch and some jobs that are expected to report failures. We can do that with the [mbed-tls-pr-ci-testing](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/) job after reconfiguring it to point to the desired branch of mbedtls-test, then kicking off some [PR jobs](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/).

* [ ] [2.28 release](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/374/)
* [ ] [pr-merge with expected failure](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-759-merge/3/)

2022-02-22 09:29 UTC, mpg commented
Testing looks good to me, but I want to clarify something: what do you mean when you write `RUN_BASIC_BUILD_TEST @ 20.04`? Looking at the job, it seems to me that `basic-build-test.sh` was only run on 16.04 as usual. But the job built the 20.04 image successfully. (Same for `all.sh`: it ran mostly on 16.04, some components on 18.04, and none on 20.04 AFAICS.)

Said otherwise, I think we have sufficient testing to be confident that we can merge this PR without breaking anything which is the goal.

I don't think we've tested how `all.sh` and `basic-build-test.sh` would run on the 18.04 or 20.04 images, but that's IMO out of scope for this task will be done later.

2022-02-22 09:52 UTC, gilles-peskine-arm commented
> Looking at the job, it seems to me that basic-build-test.sh was only run on 16.04 as usual. But the job built the 20.04 image successfully. (Same for all.sh: it ran mostly on 16.04, some components on 18.04, and none on 20.04 AFAICS.)

> I don't think we've tested how all.sh and basic-build-test.sh would run on the 18.04 or 20.04 images, but that's IMO out of scope for this task will be done later.

Right, the goal here was only to update the Docker images. We're still dispatching jobs to 16.04 if possible, otherwise 18.04, and now 20.04 added as a third option. But since all current jobs can run on either 16.04 or 20.04, nothing is getting run on 20.04 yet.

2022-02-22 09:52 UTC, merged