Adding coverity push to nightly job
ARMmbed/mbedtls-test pull request #33
Opened 2022-01-28 11:02 UTC by paul-elliott-arm

## Description

Add a job to push to the coverity scan branch to the nightly tests.

Coverity push is conditional on new environment variable PUSH_COVERITY, so future nightly jobs will have to have that variable turned on in order to enable.

Coverity push will only happen if the nightly is running on development branch.

## Testing.

This has been tested via the TEST_BRANCH variable, and found to be working.

2022-02-02 16:15 UTC, yanesca reviewed
@paul-elliott-arm could you please post a link to the successful run you mentioned above?

2022-02-02 16:15 UTC, yanesca commented on vars/gen_jobs.groovy
> +                            sh 'git push -u origin HEAD:coverity_scan'
Why do we need the `-u` switch here?

2022-02-02 16:15 UTC, yanesca commented on vars/gen_jobs.groovy
> +    if (env.PUSH_COVERITY == "true") {
I think it would be better to add this as a parameter to the `gen_release_jobs()` method, like we do it with `run_examples`. At least for now; if it is an environment variable we would need to change the job configuration, to which we don't have access yet and would mean a communication overhead.

2022-02-04 17:00 UTC, gilles-peskine-arm commented on vars/gen_jobs.groovy
> +
I guess the idea is to turn on `PUSH_COVERITY` in the nightly? But shouldn't there also be a way to do the pushing without invoking the test-related stuff (sanity checks, docker images, final report, etc.)?

2022-02-04 17:11 UTC, yanesca commented on vars/gen_jobs.groovy
> +    if (env.PUSH_COVERITY == "true") {
I don't have a problem with having it as an environment variable in the long term. In the short term however if we make it an environment variable, then we'll need to ask the OpenCI team that they add this parameter to the nightly on their side as well.

2022-02-04 17:15 UTC, yanesca commented on vars/gen_jobs.groovy
> +
I think for now it is fine to push it only in the nightly. If we want to do coverity without the nightly, we can just push directly. When we remove Travis from the equation, we might need to think about triggering Coverity without the test-related stuff, but until then I think this should be enough.

2022-02-08 18:53 UTC, paul-elliott-arm commented on vars/gen_jobs.groovy
> +                            sh 'git push -u origin HEAD:coverity_scan'
A slight muscle memory issue of mine. I conditioned myself to use -u, despite not really needing to.

2022-02-08 18:54 UTC, paul-elliott-arm commented on vars/gen_jobs.groovy
> +    if (env.PUSH_COVERITY == "true") {
Ok, reverted to just a boolean for now, we can as you say revisit this when the CI transition is over.

2022-02-08 18:57 UTC, paul-elliott-arm commented on vars/gen_jobs.groovy
> +
See above. We can for the minute still push to coverity_scan manually. If we remove travis, then as you say, an environment variable would be required in order to trigger scan manually. This can be looked at as and when any transition happens.

2022-02-08 18:57 UTC, paul-elliott-arm commented
Successful run of new code here : https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/361/

2022-02-08 19:28 UTC, gilles-peskine-arm commented on vars/gen_jobs.groovy
> +    if (env.PUSH_COVERITY == "true") {
By making this unconditional, we can't do a test run of the release code flow (e.g. to test changes to the nightly job) without pushing to coverity. I don't see how to resolve this without an environment variable. Controlling the Coverity push from the job configuration or parameters is a good thing.

Adding a parameter to the nightly is a trivial request. I don't understand why this is a concern at all.

2022-02-08 19:33 UTC, gilles-peskine-arm requested changes
Looks good to me apart from the push_coverity being forced on.

2022-02-08 19:33 UTC, gilles-peskine-arm commented on vars/gen_jobs.groovy
> +    if (push_coverity) {
`push_coverity` should be an environment variable, set by the job configuration or parameters. See https://github.com/ARMmbed/mbedtls-test/pull/33#discussion_r801986371

2022-02-08 19:33 UTC, gilles-peskine-arm commented on vars/mbedtls.groovy
> +        jobs = jobs + gen_jobs.gen_release_jobs(label_prefix, false, false)
Sorry for not catching this earlier, but I'm not convinced doing this in parallel with the testing is right. Shouldn't we only push to coverity if the functional tests have passed?

2022-02-09 08:52 UTC, yanesca commented on vars/gen_jobs.groovy
> +    if (env.PUSH_COVERITY == "true") {
It is indeed a trivial request, avoiding it still would have saved latency and effort. I want to get this done ASAP and not waste effort on it. At this point however, I feel that it is indeed more efficient to introduce that environment variable than continue discussing this.

@paul-elliott-arm I am sorry for flip-flopping on this.

2022-02-09 08:59 UTC, yanesca commented on vars/mbedtls.groovy
> +        jobs = jobs + gen_jobs.gen_release_jobs(label_prefix, false, false)
Since everything landing on the release branches passes CI, the nightly should pass consistently. Practical experience supports this as well: we have mostly intermittent faults and infrastructure issues making the nightly fail and even in the face of this it passes consistently most of the time.

Even if the nightly fails, I don't see any harm in pushing to coverity anyway.

2022-02-09 09:08 UTC, yanesca submitted a review, later dismissed
Looks good to me and as mentioned above (https://github.com/ARMmbed/mbedtls-test/pull/33#discussion_r802406596), I am happy with re-introducing the environment variable as well.

2022-02-09 14:48 UTC, paul-elliott-arm commented
Put the environment variable back (apologies for force push). See comment above about when to push above.

Succesful test run : https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/365/

2022-02-09 14:50 UTC, yanesca approved these changes
Looks good to me.

2022-02-09 16:24 UTC, gilles-peskine-arm approved these changes

2022-02-09 16:28 UTC, merged

2022-02-09 16:34 UTC, gilles-peskine-arm commented
I added the `PUSH_COVERITY` parameter to the [nightly job](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/) (default on) and to the [manual release job](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-new) (default off). Paul had already added it to the [testing job](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing) (also default off).

So starting tonight we should have daily pushes to the coverity branch.