Condition Open CI changes based on Jenkins URL
ARMmbed/mbedtls-test pull request #34
Opened 2022-01-31 02:48 UTC by arthur-she

Modify the build script to fit two CIs, Trustedfirmware OpenCI and ARM internal CI.

2022-01-31 06:44 UTC, arthur-she commented
Test PR: https://github.com/arthur-she/mbedtls/pull/4
Test job:
  [PR head](https://ci.staging.trustedfirmware.org/view/Arthur%20MbedTLS/job/arthur-mbed-tls-pr-head/view/change-requests/job/PR-4-head/1/)
  [PR merge](https://ci.trustedfirmware.org/job/arthur-2-mbed-tls-pr-merge/view/change-requests/job/PR-4-merge/2/)

2022-01-31 06:47 UTC, arthur-she commented
Hi @yanesca ,
Could you please have a look?

Thank you

Arthur

2022-01-31 15:51 UTC, bensze01 requested changes
Most of the changes seem reasonable, but removing the `static` qualifier will break our jobs on the internal CI.

2022-01-31 15:51 UTC, bensze01 commented on vars/common.groovy
> +@Field docker_tags = is_open_ci_env ? [('ubuntu-16.04'):'xenial', ('ubuntu-18.04'):'bionic'] : [:]
Removing the `static` qualifier here will break the jobs on the internal CI - `gen_jobs.gen_dockerfile_builder_job()` will populate the wrong map if it is an instance field, rather than a class one.

A better solution would be to include this logic in `init_docker_images()` and populate the map there in the short term, while `gen_jobs.gen_dockerfile_builder_job()` doesn't work on OpenCI.

2022-01-31 15:51 UTC, bensze01 commented on vars/mbedtls-release-Jenkinsfile
> +            common.init_docker_images()
If support for automatically updating docker images is not yet available on OpenCI, I think this logic would better fit inside `common.init_docker_images()`

2022-02-01 05:36 UTC, arthur-she commented on vars/mbedtls-release-Jenkinsfile
> +            common.init_docker_images()
Hi @bensze01 , @yanesca 
Thanks for your review. I will revise it.
Regarding the docker image, currently, for both TF-A and TF-M, we use a [Jenkins job](https://ci.trustedfirmware.org/job/ci-dockerfiles-deployment/) to monitor any merge activities on the [dockerfile repository](https://git.trustedfirmware.org/ci/dockerfiles.git/).
Gerrit will trigger the job to build the new docker image then push it to the [trustedfirmware](https://hub.docker.com/u/trustedfirmware) docker hub registry.
If we set up another Jenkins job, is it possible for you to create a webhook on this repository then the job can rebuild the docker image upon the latest dockerfile?

Thank you,

Arthur

2022-02-01 08:55 UTC, gilles-peskine-arm commented on vars/mbedtls-release-Jenkinsfile
> +            common.init_docker_images()
How do you test a Dockerfile update before making its image the official one?

2022-02-01 10:22 UTC, bensze01 commented on vars/mbedtls-release-Jenkinsfile
> +            common.init_docker_images()
To expand a bit on Gilles's question:

Currently, we take advantage of the fact that multiple docker images can exist in parallel on our docker repo to test upcoming changes to the Dockerfiles.

If you create a branch on this repo, and point the parametrized job at your branch, `gen_jobs.gen_dockerfile_builder_job()` will recognize if the git hash of the Dockerfile changed, build the missing docker image and push it so that it can be tested.

This way the testing / update process for our Dockerfiles / images is the same as the one for our groovy scripts.

2022-02-02 05:11 UTC, arthur-she commented on vars/mbedtls-release-Jenkinsfile
> +            common.init_docker_images()
Hi @gilles-peskine-arm , @bensze01 ,
Thanks for the explanation.
I've revised the patch. Now we support automatically updating docker images on the Open CI.

Test job [here](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-nightly-tests/57/consoleFull).

One question, how do you clean the stale images?

Thanks

2022-02-04 02:44 UTC, arthur-she commented on vars/mbedtls-release-Jenkinsfile
> +            common.init_docker_images()
To expand a bit on my question :)

What I am thinking about is that a new image will be created and pushed to the Docker registry once the dockerfile is changed.
After some time, the docker registry might contain many images which may no longer be used.

Will it happen?

2022-02-04 11:20 UTC, bensze01 commented on vars/mbedtls-release-Jenkinsfile
> +            common.init_docker_images()
@arthur-she It's a fair point. I raised this with the internal CI team at the time, and they told me not to worry about it, since the cost to host the images was negligible.

I think we can leave it as is for now, then set up a cron job / some logic in existing jobs to clean out stale images once we have OpenCI up and running. In theory, (with proper locking) we could even simply delete any image older than x days, and any images that are actually used would get re-generated.

2022-02-04 11:30 UTC, gilles-peskine-arm commented on vars/mbedtls-release-Jenkinsfile
> +            common.init_docker_images()
> we could even simply delete any image older than x days, and any images that are actually used would get re-generated

I'd prefer not to do that. Regenerating an image can fail if a server it depends on is down or has moved. We've had this problem before. If old images automatically get deleted, we should have a way to mark some as persistent.

2022-02-04 11:32 UTC, bensze01 commented on vars/mbedtls-release-Jenkinsfile
> +            common.init_docker_images()
Sure. It should be fairly simple to exclude the images that match the git hashes of the Dockerfiles on the HEAD of the master branch.

2022-02-04 17:50 UTC, gilles-peskine-arm requested changes
On code inspection, this looks correct (for the Arm CI), but slightly overcomplicated in a couple of places.

Test runs on Arm CI:
* https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/360/ — ok
* https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-758-head/ — in progress
* https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-758-merge/ — in progress

I haven't reviewed the suitability for Open CI.

2022-02-04 17:50 UTC, gilles-peskine-arm commented on vars/gen_jobs.groovy
> +export ARMLMD_LICENSE_FILE="${armlmd_license_file}"
This overrides the setting in the Docker image. We did it that way because the license server moved at a time when a bug prevented us from updating the Docker images. This bug has been resolved but we never got around to removing the workaround. Please remove this line now, rather than building on it.

2022-02-04 17:50 UTC, gilles-peskine-arm commented on vars/gen_jobs.groovy
> +    def check_docker_image_open_ci = "docker manifest inspect $common.docker_repo:$tag > /dev/null 2>&1"
Why not define `check_docker_image` based on `common.is_open_ci_env` here?

2022-02-04 17:56 UTC, gilles-peskine-arm commented on vars/gen_jobs.groovy
> +export ARMLMD_LICENSE_FILE="${armlmd_license_file}"
https://github.com/ARMmbed/mbedtls-test/pull/31 is removing the workaround.

2022-02-04 18:19 UTC, bensze01 requested changes
Agree with Gilles, this looks good overall. Just one additional warning I'd like to fix on the OpenCI side.

2022-02-04 18:19 UTC, bensze01 commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +ARG ARMLMD_LICENSE_FILE=8225@armcc.licenses.mbedcloudtesting.com
This license server has been dead for a while, we just never got around to removing it.
Please replace the default with the internal CI's values, as per [Gilles's comment](https://github.com/ARMmbed/mbedtls-test/pull/34/commits/54305920b3cb055a5766ba2a83ca10f1aafca114#r799656032).

```suggestion
ARG ARMLMD_LICENSE_FILE=7010@10.6.26.52:7010@10.6.26.53:7010@10.6.26.54:7010@10.6.26.56
```

2022-02-04 18:19 UTC, bensze01 commented on vars/gen_jobs.groovy
> +                        "auth": '${TOKEN}'
Interpolating sensitive variables produces the following warning:
```
Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.
		 Affected argument(s) used the following variable(s): [TOKEN]
		 See https://jenkins.io/redirect/groovy-string-interpolation for details.
```

So escape the dollar sign, and let the shell use the environment variable:
```suggestion
                        "auth": '\${TOKEN}'
```

2022-02-05 04:34 UTC, arthur-she commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +ARG ARMLMD_LICENSE_FILE=8225@armcc.licenses.mbedcloudtesting.com
This change also applies to ubuntu-18.04/Dockfile, right?

2022-02-05 05:51 UTC, arthur-she commented on vars/mbedtls-release-Jenkinsfile
> +            common.init_docker_images()
Agree with you. Let's leave it as it is for now then find some way to clean up later.

2022-02-05 10:27 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +ARG ARMLMD_LICENSE_FILE=8225@armcc.licenses.mbedcloudtesting.com
Yes. Please note that [we're rewriting the 18.04 dockerfile to apply a number of changes we previously made to the 16.04 dockerfile](https://github.com/ARMmbed/mbedtls-test/pull/31). I think it would be easier to rebase your changes on top of #31 since #31 is an almost complete rewrite of the 18.04 dockerfile.

2022-02-06 00:53 UTC, arthur-she commented on vars/gen_jobs.groovy
> +export ARMLMD_LICENSE_FILE="${armlmd_license_file}"
Done :)

2022-02-06 00:53 UTC, arthur-she commented on vars/gen_jobs.groovy
> +    def check_docker_image_open_ci = "docker manifest inspect $common.docker_repo:$tag > /dev/null 2>&1"
Done :)

2022-02-06 00:53 UTC, arthur-she commented on vars/gen_jobs.groovy
> +export ARMLMD_LICENSE_FILE="${armlmd_license_file}"
Done :)

2022-02-07 06:16 UTC, arthur-she commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +ARG ARMLMD_LICENSE_FILE=8225@armcc.licenses.mbedcloudtesting.com
I can rebase my changes on top of #31, however, I saw there are several items on the TODO list.
Would it be better to do it after #31 get merged?

Thanks

2022-02-07 07:52 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +ARG ARMLMD_LICENSE_FILE=8225@armcc.licenses.mbedcloudtesting.com
@arthur-she If you mean the investigation of test failures on 20.04, those are follow-ups: the objective of #31 is to have a docker image with 20.04, but we won't yet be running the tests on it. I think #31 just needs a few minor changes. I don't know how soon @minosgalanakis can make them though — Minos, when do you think you'll have time to rework #31?

2022-02-07 15:26 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +ARG ARMLMD_LICENSE_FILE=8225@armcc.licenses.mbedcloudtesting.com
`outcomes.csv` is corrupted in a few places. It looks like a race condition where two concurrent threads were writing to the same file (either `outcomes.csv` itself, or one of the per-job files it's assembled from) and their writes got intermixed.

I've never seen this happen before. So either it's a very rare race condition that you were unlucky to be the first to discover (maybe due to different scheduling or load patterns on your Jenkins instance), or it's a race condition caused by your system having more concurrency somewhere.

I'll look a bit more closely to see if I can guess where the corruption happened.

2022-02-07 18:50 UTC, arthur-she commented on vars/common.groovy
> +    content = is_open_ci_env ? "TF OpenCI: ${env.BRANCH_NAME} ${context}" : "${env.JENKINS_URL} ${env.BRANCH_NAME} ${context}"
That's a good idea.
Done :)

2022-02-07 18:58 UTC, arthur-she commented on vars/gen_jobs.groovy
>                      image_exists = sh(script: test_image_exists_sh, returnStatus: true) == 0
Thanks for the suggestion.
Done

2022-02-07 20:01 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +ARG ARMLMD_LICENSE_FILE=8225@armcc.licenses.mbedcloudtesting.com
Scratch that, the explanation is a lot simpler. Some jobs ran out of disk space at various times. For example [`all_u16-test_no_pem_no_fs
`](https://ci.staging.trustedfirmware.org/job/arthur-mbed-tls-nightly-tests/14/execution/node/977/log/) ran out during the build, [`all_u16-test_ref_configs`](https://ci.staging.trustedfirmware.org/job/arthur-mbed-tls-nightly-tests/14/execution/node/916/log/) ran out when it tried to update a state file (and then failed to update the Jenkins log as well?), and some ran out while writing to their outcome file, resulting in missing parts including line breaks.

2022-02-07 21:07 UTC, gilles-peskine-arm commented on vars/common.groovy
> +    content = is_open_ci_env ? "TF OpenCI: ${env.BRANCH_NAME} ${context}" : "Internal CI: ${env.JENKINS_URL} ${env.BRANCH_NAME} ${context}"
`Internal CI: ${env.JENKINS_URL}` is redundant. But why not simply print `${env.JENKINS_URL}` in all cases?

2022-02-07 21:10 UTC, bensze01 commented on vars/common.groovy
> +    content = is_open_ci_env ? "TF OpenCI: ${env.BRANCH_NAME} ${context}" : "Internal CI: ${env.JENKINS_URL} ${env.BRANCH_NAME} ${context}"
That's what it was before the most recent version - I'm leaning more towards removing the URL instead, to reduce visual noise / make it more helpful to contributors who might not now what the URLs mean.

It's a bit more obvious that they can see the "Open" CI logs, but not the internal ones.

2022-02-07 21:35 UTC, arthur-she commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +ARG ARMLMD_LICENSE_FILE=8225@armcc.licenses.mbedcloudtesting.com
Yeah, I rebuilt the tests and got the "no space left on device" error. Trying to increase the volume size of our AMI now.

2022-02-08 01:58 UTC, arthur-she commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +ARG ARMLMD_LICENSE_FILE=8225@armcc.licenses.mbedcloudtesting.com
After increasing the volume size, I got the [build](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-nightly-tests/85/console) successfully. 
I also rebased my changes.
Please have a look.

Thanks

2022-02-10 03:12 UTC, arthur-she commented on vars/common.groovy
> +    content = is_open_ci_env ? "TF OpenCI: ${env.BRANCH_NAME} ${context}" : "Internal CI: ${env.JENKINS_URL} ${env.BRANCH_NAME} ${context}"
@gilles-peskine-arm , @bensze01 ,
Is there anything else I can help with for this PR?

2022-02-10 19:16 UTC, arthur-she commented on vars/common.groovy
> +    content = is_open_ci_env ? "TF OpenCI: ${env.BRANCH_NAME} ${context}" : "Internal CI: ${env.JENKINS_URL} ${env.BRANCH_NAME} ${context}"
Sorry, my fault.
I've removed the URL.

2022-02-22 09:54 UTC, gilles-peskine-arm commented
We've merged #31. Sorry it took us a bit longer than anticipated. There are conflicts in the Docker files now, so please rebase this pull request.

2022-02-23 04:02 UTC, arthur-she commented
Hi @gilles-peskine-arm ,
Thank you so much.
I've rebased my change.
Please have a look.

2022-02-23 09:40 UTC, gilles-peskine-arm commented
I'm afraid the rebase doesn't look right. You're re-applying some of Minos's changes that were later overridden. Can you please rebase your own changes on top of e1a61250a3ec7f6191044f9f7c510370efdd479f? The [commit list](https://github.com/ARMmbed/mbedtls-test/pull/34/commits) shouldn't have Minos's commits anymore.

2022-02-24 00:25 UTC, arthur-she commented
Sorry about that.
Since this branch is a mess and hard to rebase, I would prefer to close this pr and create another one.

2022-02-24 00:25 UTC, closed without merging