Add branch name to nightly email notifications
ARMmbed/mbedtls-test pull request #36
Opened 2022-02-09 17:36 UTC by paul-elliott-arm

Make nightly results easier to see at a glance (and filter) by adding the branch name to the email subject.

Successful test run here: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/366/

2022-02-09 22:38 UTC, gilles-peskine-arm submitted a review, later dismissed
LGTM

I trust you received the email as expected?

2022-02-09 22:53 UTC, paul-elliott-arm commented
> LGTM
> 
> I trust you received the email as expected?

Indeed I did.

2022-02-28 15:03 UTC, gabor-mezei-arm approved these changes
LGTM

2022-03-01 13:38 UTC, gilles-peskine-arm commented
Please rebase and retest.

2022-03-02 17:08 UTC, paul-elliott-arm commented
Rebased to fix conflicts.

2022-03-02 19:18 UTC, gilles-peskine-arm commented
Test run (with your patch to make sending the email independent of the trigger): https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/385/

2022-03-02 19:22 UTC, gilles-peskine-arm requested changes
Looks good to me.

2022-03-02 19:22 UTC, gilles-peskine-arm commented on vars/common.groovy
> +        subject = is_open_ci_env ? "TF Open CI ${name} failed!" : "Internal CI ${name} failed! (branch: ${branch})"
Adding the branch name should be independent of which CI ran.

```
subject = ((is_open_ci_env ? "TF Open CI" : "Internal CI") +
           (failed_builds ? "failed" : "passed") +
           "! (branch: ${branch})")
```
or something

2022-03-04 19:21 UTC, paul-elliott-arm commented
Successful test run in https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/388/

2022-03-04 19:22 UTC, gilles-peskine-arm approved these changes
Approved pending CI validation (one passed email and one failed email)

2022-03-04 19:22 UTC, gilles-peskine-arm commented on vars/common.groovy
> +
?

2022-03-04 20:08 UTC, paul-elliott-arm commented on vars/common.groovy
> +
No idea, removed.

2022-03-04 20:08 UTC, paul-elliott-arm commented
> Approved pending CI validation (one passed email and one failed email)

How does one trigger a failed build, or is this a case of another hack?

2022-03-05 12:38 UTC, gilles-peskine-arm commented
> How does one trigger a failed build

Run on a branch (or pull request as applicable) that has test failures, such as https://github.com/ARMmbed/mbedtls-restricted/pull/759.

2022-03-07 15:24 UTC, gabor-mezei-arm approved these changes
LGTM

2022-03-08 22:24 UTC, paul-elliott-arm commented
Finally. Successful failure test : https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/391/

2022-03-10 18:47 UTC, gilles-peskine-arm approved these changes
Looks good to me (assuming the emails sent by the test jobs were ok).

2022-03-10 18:48 UTC, merged